kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: k8splus-exec
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/exec
    verbs:
      - "*"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: k8splus-exec
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8splus-exec
subjects:
- kind: ServiceAccount
  name: k8splus-exec
  namespace: k8splus-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8splus-exec
  namespace: k8splus-system